apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster

name: test-bare-metal

cloudProvider:
  none: {}

versions:
  kubernetes: 1.33.0

apiEndpoint: 
  host: 135.181.223.235
  port: 6443

controlPlane:
  hosts:
    -
      sshPort: 22
      sshPrivateKeyFile: /Users/dev/enableit/test-kubeaid-cli/robot-priv
      publicAddress: 135.181.223.235
      privateAddress: 135.181.223.235

clusterNetwork:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  cni:
    external: {}
  kubeProxy:
    skipInstallation: true

machineController:
  deploy: false

operatingSystemManager:
  deploy: false

staticWorkers:
  hosts:
    -
      sshPort: 22
      sshPrivateKeyFile: /Users/dev/enableit/test-kubeaid-cli/robot-priv
      publicAddress: 65.21.130.86
      privateAddress: 65.21.130.86

      labels: 
        node-role.kubernetes.io/worker: ""
      taints: 
        []
    -
      sshPort: 22
      sshPrivateKeyFile: /Users/dev/enableit/test-kubeaid-cli/robot-priv
      publicAddress: 65.21.130.85
      privateAddress: 65.21.130.85

      labels: 
        node-role.kubernetes.io/worker: ""
      taints: 
        []

dynamicWorkers: []

helmReleases:
  - repoURL: https://helm.cilium.io/
    chart: cilium
    version: 1.17.5
    releaseName: cilium
    namespace: cilium
    wait: true
    values:
      - inline:
          operator:
            replicas: 1
            rollOutPods: true
            priorityClassName: system-node-critical
          kubeProxyReplacement: "true"
          k8sServiceHost: 135.181.223.235
          k8sServicePort: 6443
          ipam:
            mode: kubernetes
          rollOutCiliumPods: true
          priorityClassName: system-node-critical
          hubble:
            metrics:
              enabled:
                - dns:query;ignoreAAAA
                - drop
                - tcp
                - flow
                - icmp
                - http
            relay:
              enabled: true
              rollOutPods: true
            ui:
              enabled: true
              rollOutPods: true
